// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhWDthu4dj_N56oo29IdjzfiFEUnWshro',
    appId: '1:725431561617:web:07a8e1ee3eae896ceabe30',
    messagingSenderId: '725431561617',
    projectId: 'gemini-app-46735',
    authDomain: 'gemini-app-46735.firebaseapp.com',
    storageBucket: 'gemini-app-46735.appspot.com',
    measurementId: 'G-BFY1XGVY5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5t4Ber4f0stRoot5WnvJAqAncl8zDTIQ',
    appId: '1:725431561617:android:0872e70a98af4ef0eabe30',
    messagingSenderId: '725431561617',
    projectId: 'gemini-app-46735',
    storageBucket: 'gemini-app-46735.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBjK8wndx_2KlMb7cPOUmKdMJMvwxifxQ',
    appId: '1:725431561617:ios:456925b314ef509feabe30',
    messagingSenderId: '725431561617',
    projectId: 'gemini-app-46735',
    storageBucket: 'gemini-app-46735.appspot.com',
    iosBundleId: 'com.example.geminiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBjK8wndx_2KlMb7cPOUmKdMJMvwxifxQ',
    appId: '1:725431561617:ios:456925b314ef509feabe30',
    messagingSenderId: '725431561617',
    projectId: 'gemini-app-46735',
    storageBucket: 'gemini-app-46735.appspot.com',
    iosBundleId: 'com.example.geminiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhWDthu4dj_N56oo29IdjzfiFEUnWshro',
    appId: '1:725431561617:web:6e1b06b0bd95f6a2eabe30',
    messagingSenderId: '725431561617',
    projectId: 'gemini-app-46735',
    authDomain: 'gemini-app-46735.firebaseapp.com',
    storageBucket: 'gemini-app-46735.appspot.com',
    measurementId: 'G-1BR41WDVRQ',
  );
}
